### PR TITLE
Added new versions of android

### PR DESCRIPTION
**Pull request by ascripcaru**

### CODE REVIEW

**Comment by jlipps** [comment]
I merged this, however appium-dot-app is no longer maintained and these changes will probably not be published. We're working on https://github.com/appium/appium-desktop instead.

**Comment by Astro03** [comment]
@jlipps  i can publish it if you want, but like you said, i thought it was
going to be the new app.

**Comment by jlipps** [comment]
If you feel like it you can @Astro03 but I'm not sure it's worth it.

**Comment by Astro03** [comment]
okay, then i won't :)

**Comment by ascripcaru** [comment]
@Astro03 since appium-desktop is still in progress could you do a release for this app in the mean time? now I need to switch between emulators when inspecting and when I run the tests.

**Pull request merged**
