### PR TITLE
Update to work with xcode 7.3

### PR DESCRIPTION
**Pull request by norekinc**
PR includes:
- updates that it's able to build with xcode 7.3
- remove Selenium.framework, create Podfile to install Selenium from cocoapods 
- fix sending capabilities, that are mandatory for server v1.5.0+

### CODE REVIEW

**Comment by Astro03** [comment]
@penguinho want to take a look?

**Comment by edgy360** [comment]
I certainly agree that keeping a framework under Git isn't good practice, but using pods will introduce difficulties for those running from source in strict enterprise environments.

For example, I work behind proxies and have difficultly in resolving dependencies in this way (both due to proxy settings and also having pods blocked as a cross-company default list). Also, we have restrictions from using dependencies that aren't "there" when they are reviewed by security (i.e. some high security environments disallow resolving dependencies from the outside). Ideally anyone who wants to contribute to Appium should be able to do so without installing extra software apart from Xcode in my opinion.

**Comment by penguinho** [comment]
if this is the version @Astro03 sent me, it looks good for the most part except the ios versions doesn't seem to able do taps or send keys in inspector

**Comment by Astro03** [comment]
@penguinho  - that is the version i sent you - plus a few minor changes.
@edgy360 - so what do we want to do then? i honestly have no idea what pods are (not an xcode coder)

**Comment by norekinc** [comment]
@edgy360 The question is what is more unbearable: resolving depedencies behind the wall or keep up with frameworks versions kept locally in the repo. I think it's the responsibility for the person behind the firewall/proxy, to have local copy of the external library up-to-date - in case if he can't access it normally, and have a local `Podfile` change with `pod 'xyz' , :path => '/a/b/c'`. But that's my personal opinion

**Comment by bootstraponline** [comment]
Google uses [cocoapods](http://thenextweb.com/insider/2015/05/28/google-is-embracing-cocoapods-to-bring-its-services-to-ios-developers/) to distribute Google Maps libs and others. They even produced a [YouTube video on Cocoapods](https://www.youtube.com/watch?v=iEAjvNRdZa0). This is a very popular way of managing dependencies. I'm in favor of using cocoapods.

**Comment by edgy360** [comment]
Sure, if that's what everyone uses then it's fine. I just know in my workplace we cannot use Cocapods for numerous reasons (enterprise), so it would be great if you could leave some optional alternative route for those who are unable to use it.

**Comment by bootstraponline** [comment]
If we check in the pods then it should work without internet.

**Comment by Astro03** [comment]
sweet.. sounds like it's a done deal then :).. merging

**Pull request merged**
